service:
  log_level: info

plugins:
  - ./bin/output_plugin.so

pipeline:
  inputs:
    - name: dummy
      dummy: '{"name": "John"}'

  outputs:
    - name: ip812
      match: '*'
      LogLevel: debug 
      Endpoint: localhost:4317
    - name: ip812
      match: '*'
      LogLevel: debug 
      Endpoint: localhost:4318
    - name: ip812
      match: '*'
      LogLevel: debug 
      Endpoint: localhost:4319
