service:
  log_level: info

plugins:
  - ./bin/output_plugin.so

pipeline:
  inputs:
    - name: dummy
      dummy: '{"name": "John"}'

  outputs:
    - name: ip812
      match: '*'
      logLevel: debug 
      endpoint: localhost:4317
      clientType: stdout
